### ISSUE TITLE
doHover works but diagnostic floating window is garbled

### ISSUE THREAD

**Issue by npearson72** [hexh250786313/coc-pretty-ts-errors#3]
Here is `doHover`

![Screenshot 2024-05-19 at 12 43 47 PM](https://github.com/hexh250786313/coc-pretty-ts-errors/assets/1323414/e59d93bf-9470-4064-adca-594035424f4a)

Here is diagnostic floating window

![Screenshot 2024-05-19 at 12 43 55 PM](https://github.com/hexh250786313/coc-pretty-ts-errors/assets/1323414/2af2bc9c-a65e-452e-b708-763aa0e803bc)

I have the following setting enabled: `"pretty-ts-errors.mode": 2`

Thank you for the great plugin!

**Comment by hexh250786313** [comment]
@npearson72 Thanks for the feedback.

I can't reproduce it. Please provide your `coc-settings.json`.

**Comment by hexh250786313** [comment]
@npearson72 Perhaps your coc.nvim is missing a commit that highlights the diagnostic panel, try updating coc.nvim to the latest version!

See [README](https://github.com/hexh250786313/coc-pretty-ts-errors?tab=readme-ov-file#usage):
> And make sure your coc.nvim includes the pr https://github.com/neoclide/coc.nvim/commit/9c079ad79d66d4ede7886cc4094a822352559502 which gives diagnostic floating window highlight.

**Comment by npearson72** [comment]
That was it. I just updated my version of coc-nvim, and it's working now. Thank you!

Also, is there a way to configure it so it only shows the pretty message? Right now the pretty message is on top and the ugly one is below it.

**Comment by hexh250786313** [comment]
@npearson72 No. The way coc-pretty-ts-errors operates is by simply capturing messages from the original TypeScript Language Service (ts LS) and pushing them into the diagnostics array. I have no intention of manipulating (filtering) the diagnostics from the source ts LS.

In fact, it operates similarly to the original [pretty-ts-errors](https://github.com/yoavbls/pretty-ts-errors), which also doesn't filter source diagnostic messages. I want to remain consistent with the original version.

If you are really bothered by the original diagnostic messages, you can opt to use only the doHover mode.

Of course, feel free to submit a PR for this new feature.

**Comment by hexh250786313** [comment]
@npearson72 I publish the latest `0.0.22` version. Now we can hide the original "ugly" diagnostics message! Use `:CocUpdate` to have a try!

![image](https://github.com/hexh250786313/coc-pretty-ts-errors/assets/26080416/b24c658f-53bd-480b-a8eb-cd4d624533b7)

**Comment by npearson72** [comment]
@hexh250786313 it's great. Thank you.
